#
# Generated by erpcgen 1.3.0 on Tue Dec  6 06:41:33 2016.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for Audio
class AudioClient(interface.IAudio):
    def __init__(self, manager):
        super(AudioClient, self).__init__()
        self._clientManager = manager

    def process_buf(self, data):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        outCodec = request.out_codec
        outCodec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.PROCESS_BUF_ID,
                sequence=request.sequence))
        if data is None:
            raise ValueError("data is None")
        outCodec.start_write_list(len(data))
        for _i0 in data:
            outCodec.write_uint8(_i0)
        outCodec.end_write_list()

        outCodec.write_uint32(len(data))
        outCodec.end_write_message()

        # Send request and process reply.
        self._clientManager.perform_request(request)
        inCodec = request.in_codec
        _result = inCodec.read_uint8()
        inCodec.end_read_message()
        return _result



