#
# Generated by erpcgen 1.3.0 on Tue Dec  6 06:41:33 2016.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for Audio
class IAudio(object):
    SERVICE_ID = 1
    PROCESS_BUF_ID = 1

    def process_buf(self, data):
        raise NotImplementedError()


