#
# Generated by erpcgen 1.3.0 on Tue Dec  6 06:41:33 2016.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for Audio
class AudioService(erpc.server.Service):
    def __init__(self, handler):
        super(AudioService, self).__init__(interface.IAudio.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.IAudio.PROCESS_BUF_ID : self._handle_process_buf,
            }

    def _handle_process_buf(self, sequence, inCodec, outCodec):
        # Read incoming parameters.
        _n0 = inCodec.start_read_list()
        data = []
        for _i0 in range(_n0):
            _v0 = inCodec.read_uint8()
            data.append(_v0)
        inCodec.end_read_list()

        _ = inCodec.read_uint32()
        inCodec.end_read_message()

        # Invoke user implementation of remote function.
        _result = self._handler.process_buf(data)

        # Construct reply message.
        outCodec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IAudio.SERVICE_ID,
            request=interface.IAudio.PROCESS_BUF_ID,
            sequence=sequence))
        outCodec.write_uint8(_result)
        outCodec.end_write_message()


